### ISSUE TITLE
[Question] reverse proxy

### ISSUE THREAD

**Issue by hamzux** [DexterInd/GoPiGo#135]
Hello, 

I just setup my GoPiGo to run the browser streaming app. I want to access it when away from home through another machine running nginx as a reverse proxy (ssl enabled + authentication). 

Here's my nginx config : 

`
location / {
  if ($scheme = http) {
   rewrite ^ https://$server_name$request_uri? permanent;
  }

  proxy_redirect          off;
  proxy_set_header        Host            $host;
  proxy_set_header        X-Real-IP       $remote_addr;
  proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_hide_header       X-Powered-By;
  proxy_intercept_errors on;
  proxy_buffering on;

  proxy_cache_key "$scheme://$host$request_uri";
  proxy_pass http://localIP:98;
}
`

I tested it and I can see the web page of the app but the camera does not show (it's running on port 8080 and not 98)

Any idea how to setup this?

Thanks.

**Comment by DexterInd** [comment]
Are you trying to use this example: https://github.com/DexterInd/GoPiGo/blob/master/Software/Python/Examples/Browser_Streaming_Robot/robot_web_server.py  

Or a different one for web control?

**Comment by hamzux** [comment]
yes I'm trying to use this example

thanks :)
