### ISSUE TITLE
pip upgrade stops gopigo working as expected

### ISSUE THREAD

**Issue by Rumbles** [DexterInd/GoPiGo#143]
I have my GoPiGo setup, I thought it might be an idea to update my pip install of gopigo, so I did pip install gopigo ---upgrade, this barfed, so I removed and reinstalled gopigo with pip. I tried using gopigo in the console after both and each time I got:

```
>>> gopigo.fwd()
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'fwd'
>>> print(gopigo.__file__)
/usr/local/lib/python2.7/dist-packages/gopigo/__init__.pyc
```

Previously the file showed as:

`/usr/local/lib/python2.7/dist-packages/GoPiGo-0.0.0-py2.7.egg/gopigo.pyc`

I would expect this to work, and after reinstalling by running GoPiGo/Software/Python/setup.py install and gopigo has reverted to the old version it does work.

Is this expected behaviour?

**Comment by CleoQc** [comment]
pip install currently installs a very old version. It has not been kept up to date
