### ISSUE TITLE
"Permission denied" when running compile.sh and Test.sh

### ISSUE THREAD

**Issue by kpolleck** [DexterInd/GoPiGo#210]
When running the just-installed compile.sh and Test.sh for the first time, I got "permission denied" errors even when running as root.

To fix this, I did:
  chmod 777 compile.sh
  chmod 777 Test.sh
to set the ExECUTE permission.

**Comment by DexterInd** [comment]
Hi @kpolleck , do you think we should add these commands into the readme for java?  Thanks for sharing the solution!

**Comment by marcellobarile** [comment]
Good morning @kpolleck,
I was wondering, as asked in other issues, if you are using some kind of pre-installed environment or if you have just checked out the repo from GitHub.

Thanks and have a nice day

**Comment by kpolleck** [comment]
Nothing special.  My 15-year-old son and I pretty much just assembled the kit (RaspberryPi 3 + GoPiGo2), connected a TV to the HDMI port to configure the wireless, connected via VNC and ran the python routes successfully.

Then, being Java fans, we ran:

curl -s get.pi4j.com | sudo bash

...and followed the rest of the steps in https://github.com/DexterInd/GoPiGo/tree/master/Software/Java

**Comment by marcellobarile** [comment]
Alright @kpolleck, thank you so much for the effort that you and your son are putting into this :) First of all I'll try a fresh installation with the most recent pi4j release then I'll give you an update as soon as I come up with more clues, if anything pops out from your side don't hesitate to update the issue.

Have a nice evening

**Comment by marcellobarile** [comment]
@kpolleck thank you so much for the effort that you and your son are putting into this :-) Actually you are right and you did nothing wrong; the scripts comes out with no execution rights.. which means it should be nice to specify, in the readme file, that those are supposed to be set.

Just checked out and copied/pasted as confirm:
-rw-rw-r-- 1 marcello marcello  146 Feb 28 23:47 Test.sh
-rw-rw-r-- 1 marcello marcello  327 Feb 28 23:47 compile.sh

Thank you again for having pointed it out and have a nice evening

**Comment by DexterInd** [comment]
Sounds like a great solution to me.  We could combine the installation step and setting the permissions to all of these into a bash script.  This way a user can just run an install script once, rather than do all the commands.  We can do that if you think it will help, let me know!
