### ISSUE TITLE
bash: ./camphish.sh: Permission denied

### ISSUE THREAD

**Issue by pankaj653** [DexterInd/GoPiGo#324]
bash: ./camphish.sh: Permission denied

**Comment by pankaj653** [comment]
bash: ./camphish.sh: Permission denied

**Comment by Trickster811** [comment]
Hello!! I got the same problem and I tried this to solve it:

~$ cd Camphish
~$ chmod -R 777 *

**Comment by CleoQc** [comment]
I am not sure what Camphish is supposed to be, but please don't use chmod -R 777 *
That is going to open up your whole system, way more than needed.

**Comment by Trickster811** [comment]
Thanks you guy
