### ISSUE TITLE
Firmware version mismatch

### ISSUE THREAD

**Issue by BandonRandon** [DexterInd/GoPiGo#52]
Today I got out my GoPiGo and noticed that v13 of the firmware was available on GitHub. I did a manual update to v13. 

I then ran the Dexter Industries Update script that comes with the DI version of Raspian and that reverted the firmware back to v12

I'm not sure if there is a difference between these two versions but it may make sense to have the auto updater grab v13 instead of v12.

**Comment by karan259** [comment]
The stable version for the GoPiGo firmware is v12 so that's why the DI script uses it. We'll be switching to v13 in the coming days and make it official. After that the default should be v13
