### ISSUE TITLE
vnc + gopigo = crash

### ISSUE THREAD

**Issue by spraints** [DexterInd/GoPiGo#66]
If I ssh to my gopigo robot and run `cd Desktop/GoPiGo/Software/Python/Examples/Basic\ Robot\ Control/; sudo python basic_robot.py`, everything works right. If I use vnc to connect, and run the same thing in a terminal, the raspberry pi crashes as soon as I make the robot do anything (e.g. `w` to make it go forward).

I'm probably doing something wrong, but I don't know where to start debugging.

**Comment by DexterInd** [comment]
Hey spraints, we'll give this a shot.  Haven't seen this before.

**Comment by DexterInd** [comment]
Hey spraints, just tried this to make sure I wasn't going crazy.  Worked just fine for me.  I wonder if your batteries are weak or low?  Can you try powering with a USB wall plug, as well as the batteries, in case that's the problem?  Or do you have a way to test the batteries?

**Comment by spraints** [comment]
> Can you try powering with a USB wall plug, as well as the batteries, in case that's the problem?

I've been using a wall plug, but I don't think it's the highest amperage plug that I've got. Also, I was using a usb wireless network adapter, which I assume draws some current too. I won't be able to try for a couple of days, but I'll let you know if I can get it working by changing the power supply or network connection.

**Comment by DexterInd** [comment]
Using the wall plug and a battery pack at the same yime?  That's what I
would try first, or just using batteries alone.  You may be seeing the pi
reset because of amperage draw.  If you use the wall plug alone, and the
motors and no battery, you could burn out the pi and or the gopigo.

**Comment by spraints** [comment]
Ah, that was it. I put fresh batteries in it today, and it runs around the floor just fine. Thanks!
